### PR TITLE
Andres8ezau added readme

### PR DESCRIPTION
**Pull request by Andres8ezau**
This is the rigth one! C:

### CODE REVIEW

**Comment by Vishruth-S** [comment]
@Andres8ezau  I'm sorry there seems to have been a misunderstanding. I assume you made this to resolve issue #6 . However, that issue had already been assigned to another person before. I just noticed that now, sorry 😐

**Comment by Vishruth-S** [comment]
Is it possible for you to take up issue #12 and work on that?. In the meantime, I will label this as hacktoberfest-accepted

**Comment by Andres8ezau** [comment]
Sure, Don't worry ! I will get to that C:

**Comment by Vishruth-S** [comment]
Alright. Can I assign you the issue #12  ?

**Comment by Andres8ezau** [comment]
Yes, I'm already working on that !

**Pull request closed without merging**
